#!/usr/bin/env zsh

_UTILNAME_cli_commands="
  UTILNAME help
  UTILNAME dev
"

# display help
_UTILNAME_cli_help() {
  echo "ADD TITLE FOR UTILNAME AND DESCRIPTION"
  echo
  echo "Syntax: UTILNAME <command> <<arg>...>"
  echo
  echo "Commands:"
  echo 
  echo "..."
}

_timestamp() {
  date +'%Y%m%d%k%M%S'
}

_has_logs() {
  [[ -s ~/.track/logs ]];
}

UTILNAME() {
  local command=
  local param1=
  local param2=

  if [ -z "" ] || [ $command = 'help' ]; then
    _UTILNAME_cli_help
    return 0
  fi

  # UTILNAME dev {
  if [ $command = 'dev' ]; then
    echo 'TODO: IMPLEMENT'
    # vim PATH_TO_THIS_FILE
  # }
  #
  # UTILNAME test {
  elif [ $command = 'test' ]; then
    echo 'no tests'
  # }
  #
  # display help
  else
    _UTILNAME_cli_help
  fi
}

_UTILNAME_cli_complete() {
  local commands=($(echo $_UTILNAME_cli_commands | awk '/.+/ {print $2}'))
  local completions="$(echo $commands)"
  completions="$completions$(echo 'ADDITIONAL_AUTOCOMPLETE_HERE')"
  reply=( $(compgen -W ${completions[@] -- $1}) )
}

compctl -f -K _UTILNAME_cli_complete UTILNAME
